apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resultserver
  name: resultserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resultserver
  strategy: {}
  template:
    metadata:
      labels:
        app: resultserver
    spec:
      containers:
      - image: kosifug/resultserver
        name: resultserver
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: servers-config
        env: 
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
          # value: Ugr_1
        # - name: MYSQL_USER
        #   value: Ugur
        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_DATABASE_HOST
        #   value: mysql
        resources: {}
